### ISSUE TITLE
Menü-Bereich Download

### ISSUE THREAD

**Issue by astridorth** [subugoe/metrics-website#23]
Elternseite: 
- [x] Projektmaterialien (ok)
- [x] Marketingmaterialien Logo tiefere Gliederung
- [x] Themenbezogene in About/Community aufnehmen bzw. ev. News daraus machen
- [x] gekürzter Antrag (Wordversion besorgen)
- [x] wie Anzeige für Startseite ausgesucht?

**Comment by nilswindisch** [comment]
Bearbeitet ihr das Issue noch?
