### ISSUE TITLE
Menü-Bereich News

### ISSUE THREAD

**Issue by astridorth** [subugoe/metrics-website#30]
Ziel: 4-5 News zum Start

- [x] Kick-Off: doppeltes Datum weg
- [x] Barcamp: Überschrift weg, besser formatieren
- [x] European Expert Group (Isabella) EN: erstellen (übersetzen? nicht unbedingt, probieren wie es aussieht)
- [x] Survey: entweder noch laufend oder dass wir es überhaupt gemacht haben
- [x] Slack dissemination channel durchschauen und beste raussuchen

**Comment by nilswindisch** [comment]
Alle Haken sind gesetzt, daher schliesse ich das Issue
