### ISSUE TITLE
hreflang missing?

### ISSUE THREAD

**Issue by nilswindisch** [subugoe/metrics-website#58]
Google Search Console reports a missing hreflang. Please confirm and suggest a fix.

<img width="649" alt="screenshot 2017-05-31 09 45 14" src="https://cloud.githubusercontent.com/assets/914680/26621117/dc729ac0-45e5-11e7-8099-901bb05ade49.png">

Please tell me if you need access to the Google Search Console property

**Comment by MustafaSalih** [comment]
I've found this statement by Google: "...**the language attribute within the HTML markup is something we don't use at all.**"  on https://www.seroundtable.com/google-ignores-the-html-lang-attribute-22974.html 
Here is the video conference https://youtu.be/isW-Ke-AJJU?t=55m54s
As I can see they tend to ignore that. Now I'm looking for an exact solution.

**Comment by MustafaSalih** [comment]
There are three options:
1- HTML hreflang link elements in <head> like: 
`<link rel="alternate" href="http://example.com/" hreflang="en" />`
`<link rel="alternate" href="http://example.com/en-gb/" hreflang="en-gb" />`
`<link rel="alternate" href="http://example.com/en-au/" hreflang="en-au" />`

2- hreflang HTTP headers like:
`Link: <http://es.example.com/document.pdf>; `
`rel="alternate"; hreflang="es", `
`<http://en.example.com/document.pdf>; `
`rel="alternate"; hreflang="en"`

3- Or an XML sitemap hreflang implementation like:
`<url>`
`  <loc>http://www.example.com/uk/</loc> `
`  <xhtml:link rel="alternate" hreflang="en" `
`     href="http://www.example.com/" /> `
`  <xhtml:link rel="alternate" hreflang="en-au" `
`     href="http://www.example.com/au/" /> `
`</url>`

Source: https://yoast.com/hreflang-ultimate-guide/
