### ISSUE TITLE
Implement sticky footer with flexbox

### ISSUE THREAD

**Issue by nilswindisch** [subugoe/metrics-website#59]
Replace the current implementation - which uses a fixed height on the footer and other rather ugly details - with a (cleaner) flexbox based solution. 

Please work in a separate branch and report back as you see fit.

**Comment by MustafaSalih** [comment]
I implemented a new sticky footer based on flexbox. You can see the changes on `salih-issue59` branch.

**Comment by nilswindisch** [comment]
The footer is not sticky yet…
![screenshot 2017-06-27 08 09 06](https://user-images.githubusercontent.com/914680/27573044-f58b1692-5b0f-11e7-93a0-2fde4fcb5d7d.png)

**Comment by MustafaSalih** [comment]
Sticky footer is working fine now!
![screencapture-127-0-0-1-8080-1500276959766](https://user-images.githubusercontent.com/3898949/28258898-ecb314ec-6ad3-11e7-84c6-308cc112352f.png)
